#!/usr/bin/env bash
# Build the image and run the whole app (API + React client) in one container.
set -euo pipefail

IMAGE=auth-app-server
CONTAINER=auth-app-api
DB_CONTAINER=auth-app-pg
PORT="${PORT:-3001}"
ENV_FILE=.env.docker

cd "$(dirname "$0")/.."

# Secrets are generated once and reused, so restarting the container doesn't
# invalidate every refresh token that's already out there.
if [ ! -f "$ENV_FILE" ]; then
  echo "==> Generating $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/docker-up.sh — gitignored, safe to delete and regenerate.
# host.docker.internal reaches auth-app-pg via the port it publishes on the host.
DATABASE_URL=postgres://postgres:devpass@host.docker.internal:5434/app
ACCESS_TOKEN_SECRET=$(openssl rand -hex 32)
REFRESH_TOKEN_SECRET=$(openssl rand -hex 32)
CLIENT_URL=http://localhost:${PORT}
# Browsers withhold Secure cookies over plain HTTP, which would break refresh.
COOKIE_SECURE=false
EOF
fi

echo "==> Starting database ($DB_CONTAINER)"
docker start "$DB_CONTAINER" >/dev/null

echo "==> Building image"
# --network=host: under BuildKit's default network, bun's parallel downloads
# corrupt tarballs on this host ("integrity check failed"). See AUTH.md.
docker build --network=host -t "$IMAGE" .

echo "==> Replacing container"
docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
docker run -d \
  --name "$CONTAINER" \
  -p "${PORT}:3000" \
  --add-host=host.docker.internal:host-gateway \
  --env-file "$ENV_FILE" \
  "$IMAGE" >/dev/null

echo -n "==> Waiting for health"
for _ in $(seq 30); do
  status=$(docker inspect -f '{{.State.Health.Status}}' "$CONTAINER" 2>/dev/null || echo starting)
  if [ "$status" = "healthy" ]; then break; fi
  if [ "$status" = "unhealthy" ]; then
    echo " failed"
    docker logs --tail 30 "$CONTAINER"
    exit 1
  fi
  echo -n "."
  sleep 1
done
echo " ${status}"

echo "==> Seeding users"
docker exec "$CONTAINER" bun run server/dist/seed.js

echo
echo "App running at http://localhost:${PORT}"
echo "  alice@example.com / password123"
echo "  bob@example.com   / password456"
echo "Logs: docker logs -f ${CONTAINER}   Stop: docker rm -f ${CONTAINER}"
